-- src/lang.lua
-- ApexFlow i18n — v0.34.0
-- Uso: L("texto em PT") em qualquer string visível da UI/HUD.
-- Chave = próprio texto PT (com ##id preservado). Sem tradução = mostra PT.
-- Idiomas: pt (base), en, es. Novos idiomas = nova tabela em DICT.

local M = {}

M._lang = "pt"
M.LANGS = { "pt", "en", "es" }
M.LANG_NAMES = { pt = "Português", en = "English", es = "Español" }

M.DICT = {
en = {
  ["SEÇÕES"] = "SECTIONS",
  ["Início"] = "Home",
  ["Telemetria viva da sessão"] = "Live session telemetry",
  ["Pilotos"] = "Drivers",
  ["Personalidade, brigas e aprendizado da IA"] = "AI personality, battles and learning",
  ["Corrida"] = "Race",
  ["Duração, pits, pneus e largada"] = "Length, pits, tires and start",
  ["Tela&Voz"] = "Screen&Voice",
  ["Painel na tela, telemetria e voz"] = "On-screen panel, telemetry and voice",
  ["Ajustes"] = "Settings",
  ["Visual, atualizações e bastidores"] = "Looks, updates and internals",
  ["🤖 Pilotos"] = "🤖 Drivers",
  ["🏁 Corrida"] = "🏁 Race",
  ["📡 Tela & Voz"] = "📡 Screen & Voice",
  ["⚙️ Ajustes"] = "⚙️ Settings",
  ["Quanto o grid briga"] = "How much the grid fights",
  ["0 = desfile calmo · 100 = todo mundo atacando. 50 é o meio-termo."] = "0 = calm parade · 100 = everyone attacking. 50 is the middle ground.",
  ["Ritmo e dificuldade"] = "Pace & difficulty",
  ["Deixa a IA mais rápida ou devagar no geral. 100% = jogo original."] = "Makes the AI faster or slower overall. 100% = stock game.",
  ["Ultrapassagens de verdade"] = "Real overtakes",
  ["A IA tenta passar em vez de andar em fila."] = "The AI tries to pass instead of queuing.",
  ["Várias categorias juntas"] = "Multiple classes together",
  ["Ex: protótipos + GT. Classe 1 = mais rápida."] = "E.g. prototypes + GT. Class 1 = fastest.",
  ["Pistas de reta (Monza)"] = "Straight-line tracks (Monza)",
  ["Só mexa p/ pistas de alta velocidade."] = "Only touch for high-speed tracks.",
  ["IA que aprende"] = "Learning AI",
  ["Lembra onde erra e melhora com o tempo."] = "Remembers mistakes and improves over time.",
  ["Combustível e pits"] = "Fuel & pits",
  ["Diga as voltas; a IA calcula paradas e pneus sozinha."] = "Enter the laps; the AI sorts stops and tires itself.",
  ["Largada em movimento"] = "Rolling start",
  ["Volta de apresentação em fila antes da verde. Vem desligado."] = "Formation lap in line before green. Comes off.",
  ["Painel na tela"] = "On-screen panel",
  ["Escolha o que o overlay mostra na corrida (gaps/PP)."] = "Choose what the overlay shows in the race (gaps/PP).",
  ["Visual"] = "Appearance",
  ["Cor de destaque e transparência."] = "Accent color and transparency.",
  ["Atualizações"] = "Updates",
  ["Ver se saiu versão nova."] = "Check for a new version.",
  ["Ajuda"] = "Help",
  ["O que cada parte faz, em linguagem simples."] = "What each part does, in plain language.",
  ["Dê personalidade à IA. Padrões servem p/ quase tudo."] = "Give the AI personality. Defaults work for almost everything.",
  ["Agressividade global"] = "Global aggression",
  ["Calmo"] = "Calm",
  ["Equilibrado"] = "Balanced",
  ["Agressivo"] = "Aggressive",
  ["Coragem no mergulho"] = "Dive-in courage",
  ["Empurrão na briga"] = "Battle shove",
  ["Tempo colado até atacar (s)"] = "Glued time before attacking (s)",
  ["Chance de volta voadora (%/volta)"] = "Flying lap chance (%/lap)",
  ["Racecraft (brigas e ultrapassagens)"] = "Racecraft (battles and overtakes)",
  ["Predefinições:"] = "Presets:",
  ["Predefinições Rápidas (Endurance & 24 Horas):"] = "Quick presets (Endurance & 24 Hours):",
  ["Predefinições Reais de Largada:"] = "Real start presets:",
  ["Profiles:"] = "Profiles:",
  ["Sprint (20v / 1 pit)"] = "Sprint (20 laps / 1 pit)",
  ["Club (40v / 1 pit)"] = "Club (40 laps / 1 pit)",
  ["1h (60v / 2 pits)"] = "1h (60 laps / 2 pits)",
  ["2.4h (120v / 4 pits)"] = "2.4h (120 laps / 4 pits)",
  ["4h (180v / 6 pits)"] = "4h (180 laps / 6 pits)",
  ["6h (250v / 9 pits)"] = "6h (250 laps / 9 pits)",
  ["12h Sebring (450v / 15 pits)"] = "12h Sebring (450 laps / 15 pits)",
  ["24h Le Mans (800v / 28 pits)"] = "24h Le Mans (800 laps / 28 pits)",
  ["24h Nordschleife (160v / 18 pits)"] = "24h Nordschleife (160 laps / 18 pits)",
  ["1000km / 1000 Milhas (600v)"] = "1000km / 1000 Miles (600 laps)",
  ["Chuva / Fila única (70 km/h / 90%)"] = "Rain / Single file (70 km/h / 90%)",
  ["Ativar Estratégia de Combustível / Pit-Stops"] = "Enable Fuel / Pit-Stop Strategy",
  ["Ativar Largada em Movimento"] = "Enable Rolling Start",
  ["Ativar troca de pneus"] = "Enable tire changes",
  ["Troca de Pneus"] = "Tire Changes",
  ["Trocar pneus quando estado ≤"] = "Change tires when condition ≤",
  ["Se ativado, durante a parada forçada nos boxes, a IA verificará o desgaste dos pneus. Se o estado estiver abaixo do limite configurado, pneus novos serão colocados junto com o reabastecimento."] = "When on, during forced pit stops the AI checks tire wear. Below the set threshold, fresh tires go on with the refuel.",
  ["Duração da corrida (voltas)"] = "Race length (laps)",
  ["Paradas obrigatórias nos boxes"] = "Mandatory pit stops",
  ["Pneus (Frente): "] = "Tires (Front): ",
  ["Pneus (Trás):    "] = "Tires (Rear):    ",
  ["DE: %.0f%%"] = "FL: %.0f%%",
  ["DD: %.0f%%"] = "FR: %.0f%%",
  ["TE: %.0f%%"] = "RL: %.0f%%",
  ["TD: %.0f%%"] = "RR: %.0f%%",
  ["DE: %.0f%% | DD: %.0f%% | TE: %.0f%% | TD: %.0f%%"] = "FL: %.0f%% | FR: %.0f%% | RL: %.0f%% | RR: %.0f%%",
  ["Combustível Carro 0: %.1f L / %.1f L (%.0f%%)"] = "Car 0 fuel: %.1f L / %.1f L (%.0f%%)",
  ["🏁 Monitor de Endurance & Telemetria"] = "🏁 Endurance & Telemetry Monitor",
  ["🤖 Estratégia das IAs ao vivo"] = "🤖 Live AI strategy",
  ["Voltas da prova (auto): %d"] = "Race laps (auto): %d",
  ["Voltas da prova (manual): %d"] = "Race laps (manual): %d",
  ["de %dv"] = "of %d laps",
  ["de %dv (auto)"] = "of %d laps (auto)",
  ["⛽ Pit: volta %d%s%s"] = "⛽ Pit: lap %d%s%s",
  [" · faltam %d"] = " · %d left",
  ["⛽ Sem pit agendado"] = "⛽ No pit scheduled",
  ["⛽ box AGORA (tanque no fim)"] = "⛽ box NOW (tank almost empty)",
  ["⛽ box em ~%dv (%.1f L/volta)"] = "⛽ box in ~%d laps (%.1f L/lap)",
  ["🏁 Você na volta %d"] = "🏁 You are on lap %d",
  ["Força do ritmo ( Pace )"] = "Pace strength",
  ["pit v"] = "pit lap ",
  ["sem pit"] = "no pit",
  ["manual"] = "manual",
  ["armado"] = "armed",
  ["nova!"] = "new!",
  ["v/"] = " laps/",
  ["📏 VOCÊ LIDERA"] = "📏 YOU LEAD",
  ["📏 P1 +%d volta(s)"] = "📏 P1 +%d lap(s)",
  ["📏 +%dm p/ P1"] = "📏 +%dm to P1",
  ["🔙 Atrás: %.0fm (P%d)"] = "🔙 Behind: %.0fm (P%d)",
  ["🔙 sem carro atrás"] = "🔙 no car behind",
  ["⏱ Setor %d: +%.2fs p/ P1"] = "⏱ Sector %d: +%.2fs to P1",
  ["⚖ PP: limpo"] = "⚖ PP: clean",
  ["P%d   ·   V%d   ·   %d km/h   ·   M%d"] = "P%d   ·   Lap %d   ·   %d km/h   ·   Gear %d",
  ["P%d   ·   V%d   ·   %d km/h   ·   %.1fL"] = "P%d   ·   Lap %d   ·   %d km/h   ·   %.1fL",
  ["🟢 PISTA VERDE"] = "🟢 GREEN TRACK",
  ["🟢 pista verde — AC nativo"] = "🟢 green track — native AC",
  ["🟢 Pace Car Detectado: Toyota ACTC (dj_safety_car) na liderança!"] = "🟢 Pace Car detected: Toyota ACTC (dj_safety_car) leading!",
  ["🟢 Pace Car Detectado: dj_safety_car"] = "🟢 Pace Car detected: dj_safety_car",
  ["⚠ Rolling Start pode não funcionar: funções de física ausentes nesta build do CSP."] = "⚠ Rolling Start may not work: physics functions missing in this CSP build.",
  ["⚪ Formação liderada pelo Pole Position (ou adicione o dj_safety_car no grid)."] = "⚪ Formation led by the Pole Position (or add dj_safety_car to the grid).",
  ["Marque o que quer ver no overlay:"] = "Check what to show on the overlay:",
  ["Posição / volta / velocidade"] = "Position / lap / speed",
  ["Estratégia (próximo pit / combustível)"] = "Strategy (next pit / fuel)",
  ["Sessão (pista / tempo restante)"] = "Session (track / time left)",
  ["Learning (pistas memorizadas)"] = "Learning (memorized tracks)",
  ["Extras (preset · update · detalhes)"] = "Extras (preset · update · details)",
  ["Estilo"] = "Style",
  ["Modo compacto (menos espaçamento)"] = "Compact mode (less spacing)",
  ["Barras de progresso"] = "Progress bars",
  ["Piscar alertas críticos"] = "Blink critical alerts",
  ["Escala do HUD"] = "HUD scale",
  ["Esconder parado no box (+10s)"] = "Hide when stopped in pits (+10s)",
  ["Gaps (atrás / setor) · PP"] = "Gaps (behind / sector) · PP",
  ["👁 Testar HUD"] = "👁 Test HUD",
  ["Abre a janela overlay. O botão 👁 injeta 10s de FCY + punição fake (com tag PREVIEW) p/ ver o layout sem correr."] = "Opens the overlay window. The 👁 button injects 10s of fake FCY + penalty (PREVIEW tag) to see the layout without racing.",
  ["Padrões de volta"] = "Defaults restored",
  ["✓ padrões"] = "✓ defaults",
  ["⚠️ Voltar aos padrões?"] = "⚠️ Back to defaults?",
  ["Apaga TODOS os ajustes (perfis, limites, voz, tema). Sem desfazer."] = "Erases ALL settings (profiles, limits, voice, theme). No undo.",
  ["Sim, restaurar"] = "Yes, restore",
  ["💾 Salvar"] = "💾 Save",
  ["Salvo"] = "Saved",
  ["🔄 Padrões"] = "🔄 Defaults",
  ["📊 Painel"] = "📊 Panel",
  ["Filtre por nome: “pit”, “gaps”, “PP”N…"] = "Filter by name: “pit”, “gaps”, “PP”…",
  [" · filtro ativo"] = " · filter active",
  ["⌨ filtrar…"] = "⌨ filter…",
  ["App ligado"] = "App on",
  ["App pausado"] = "App paused",
  ["○ box"] = "○ pits",
  ["O restante do app continua funcionando. Envie esse texto ao suporte."] = "The rest of the app keeps working. Send this text to support.",
  ["Detalhe: "] = "Detail: ",
  ["Erro ao desenhar a aba "] = "Error drawing tab ",
  ["Erro: "] = "Error: ",
  ["Versão instalada: v"] = "Installed version: v",
  ["Repositório: "] = "Repository: ",
  ["Changelog da v"] = "Changelog of v",
  ["Publicado em: "] = "Published on: ",
  ["Atualização disponível: v%s → v%s"] = "Update available: v%s → v%s",
  ["Versão atualizada (v"] = "Updated version (v",
  ["Nenhuma verificação realizada ainda."] = "No check performed yet.",
  ["Não consegui abrir sozinho. Digite no navegador:"] = "Couldn't open it myself. Type in your browser:",
  ["Verificação Automática"] = "Automatic Check",
  ["Verificação automática indisponível"] = "Automatic check unavailable",
  ["ℹ Verificação automática indisponível"] = "ℹ Automatic check unavailable",
  ["Esta build do CSP não expõe HTTP para o Lua. A verificação volta sozinha ao atualizar o CSP."] = "This CSP build doesn't expose HTTP to Lua. Checks resume on their own when you update CSP.",
  ["Verifica releases no GitHub via API (requer CSP com ac.webRequest)."] = "Checks GitHub releases via API (requires CSP with ac.webRequest).",
  ["Verificar na inicialização"] = "Check on startup",
  ["Intervalo entre verificações (horas)"] = "Check interval (hours)",
  ["🔍 Verificar Agora"] = "🔍 Check Now",
  ["🌐 Abrir Release"] = "🌐 Open Release",
  ["🌐 Abrir página de Releases"] = "🌐 Open Releases page",
  ["✓ Verificando atualizações..."] = "✓ Checking for updates...",
  ["Disponível durante a sessão de corrida."] = "Available during the race session.",
  ["Telemetria disponível durante a sessão de corrida."] = "Telemetry available during the race session.",
  ["Telemetria do carro ativo disponível durante a sessão."] = "Active car telemetry available during the session.",
  ["Dados das IAs aparecem durante a sessão."] = "AI data appears during the session.",
  ["Estratégia de Corrida & Endurance"] = "Race & Endurance Strategy",
  ["Configuração de duração da corrida e paradas nos boxes para corridas curtas ou de Endurance (longa duração)."] = "Race length and pit stop setup for short or Endurance (long) races.",
  ["Velocidade limite durante a volta de formação."] = "Speed limit during the formation lap.",
  ["Espaço para-choque a para-choque. 3.8 a 4.5m é o padrão das categorias reais."] = "Bumper-to-bumper gap. 3.8 to 4.5m is the real-category standard.",
  ["Distância de separação entre as duas filas (esquerda e direita)."] = "Separation between the two rows (left and right).",
  ["Ponto em que a bandeira verde é acionada. 92% a 96% corresponde à entrada da reta principal."] = "Point where the green flag waves. 92% to 96% matches the main straight entry.",
  ["Predefinições Reais de Largada:"] = "Real start presets:",
  ["Predefinições Rápidas (Endurance & 24 Horas):"] = "Quick presets (Endurance & 24 Hours):",
  ["Sem sessão — números vivos aparecem em pista "] = "No session — live numbers appear on track ",
  ["Sem sessão — o placar acende em pista "] = "No session — the board lights up on track ",
  ["🅿 no box — HUD pausado (volte à pista p/ reativar)"] = "🅿 in pits — HUD paused (back on track to resume)",
  ["central de IA, estratégia e direção de prova "] = "AI core, strategy and race direction ",
  ["Race Events HUD — Personalização"] = "Race Events HUD — Customization",
  ["Preset"] = "Preset",
  [" aplicado"] = " applied",
  ["Ajustes manuais (sem preset)"] = "Manual settings (no preset)",
  ["Antes de largar: duração, paradas e formação."] = "Before the start: length, stops and formation.",
  ["O que aparece correndo."] = "What shows while racing.",
  ["Visual"] = "Appearance",
  ["Cor de destaque e transparência."] = "Accent color and transparency.",
  ["Atualizações"] = "Updates",
  ["Ver se saiu versão nova."] = "Check for a new version.",
  ["Ajuda"] = "Help",
  ["O que cada parte faz, em linguagem simples."] = "What each part does, in plain language.",
  [" central de IA, estratégia e direção de prova "] = " AI core, strategy and race direction ",
  ["%d carros"] = "%d cars",
  ["Arredondamento dos cantos"] = "Corner rounding",
  ["Cabeçalhos compactos (sem subtítulo)"] = "Compact headers (no subtitle)",
  ["Cancelar"] = "Cancel",
  ["Chuva / Fila Única (70 km/h / 90%)"] = "Rain / Single file (70 km/h / 90%)",
  ["Ciano"] = "Cyan",
  ["Filtre por nome: “pit”, “gaps”, “PP”…"] = "Filter by name: “pit”, “gaps”, “PP”…",
  ["Formação 2x2 lado a lado na volta de apresentação, com velocidade controlada e relargada realista na reta principal ao receber a bandeira verde."] = "2x2 side-by-side formation on the presentation lap, with controlled speed and a realistic restart on the main straight for the green flag.",
  ["Gaps (atrás / setor) — PP"] = "Gaps (behind / sector) — PP",
  ["Idioma"] = "Language",
  ["Intensidade da física"] = "Physics intensity",
  ["Laranja Apex"] = "Apex orange",
  ["Largada em Movimento Realista (Rolling Start)"] = "Realistic Rolling Start",
  ["Leigo: controla o quanto as IAs brigam por posição em vez de andar em fila.\nTécnico: impaciência atrás (stuckRamp), janela de mergulho (draft commit) e empurrão."] = "Plain: how much the AI fight for position instead of queuing.\nTechnical: impatience behind (stuckRamp), dive window (draft commit) and shove.",
  ["Leigo: deixa o HUD menor e mais denso.\nTécnico: pula separadores e textos secundários."] = "Plain: makes the HUD smaller and denser.\nTechnical: skips separators and secondary text.",
  ["Leigo: escolha o que aparece no overlay ApexFlow Events (gaps/PP).\nTécnico: cada seção lê o estado do seu módulo; desligar esconde só o visual."] = "Plain: choose what the ApexFlow Events overlay shows (gaps/PP).\nTechnical: each section reads its module state; off hides only the visual.",
  ["Leigo: esconde as linhas de explicação das abas, deixa tudo menor.\nTécnico: pula o subtitle em cardTitle()."] = "Plain: hides the tab explanation lines, makes everything smaller.\nTechnical: skips the subtitle in cardTitle().",
  ["Leigo: mostra quem vai parar e quando.\nTécnico: próximos pitLaps calculados + combustível restante/aprendido."] = "Plain: shows who pits and when.\nTechnical: computed next pitLaps + remaining/learned fuel.",
  ["Leigo: mude a cor de destaque e a transparência do fundo.\nTécnico: cor de destaque (accent) e alfa do WindowBg/ChildBg."] = "Plain: change the accent color and background transparency.\nTechnical: accent color and WindowBg/ChildBg alpha.",
  ["Leigo: no box parado o painel dorme sozinho e volta na pista.\nTécnico: gate por isInPitlane/isInPit + speed < 5 por 10s."] = "Plain: stopped in the pits the panel sleeps alone and wakes on track.\nTechnical: gate on isInPitlane/isInPit + speed < 5 for 10s.",
  ["Leigo: preset atual, aviso de update, marcha/pneus/paradas da IA.\nTécnico: lê githubGetState e strategy.getState (gaps/PP)."] = "Plain: current preset, update notice, AI gear/tires/stops.\nTechnical: reads githubGetState and strategy.getState (gaps/PP).",
  ["Para atualizar: baixe a última release e substitua a pasta apps/lua/ApexFlow."] = "To update: download the latest release and replace the apps/lua/ApexFlow folder.",
  ["Rosa"] = "Pink",
  ["Roxo"] = "Purple",
  ["Transparência do fundo"] = "Background transparency",
  ["Turquesa"] = "Teal",
  ["Verde"] = "Green",
  ["Vermelho"] = "Red",
  ["Visual, updates e bastidores. Mexa uma vez e esqueça."] = "Looks, updates and internals. Set once and forget.",
  ["✓ Versão atualizada (v"] = "✓ Updated version (v",
  ["❌ Erro ao desenhar a aba "] = "❌ Error drawing tab ",
  ["❌ Erro: "] = "❌ Error: ",
  ["🎉 Atualização disponível: v%s → v%s"] = "🎉 Update available: v%s → v%s",
  ["🎨 Aparência"] = "🎨 Appearance",
  ["📚 %d pista(s)"] = "📚 %d track(s)",
  ["📚 sem dados"] = "📚 no data",
  ["📺 Abrir ApexFlow Events"] = "📺 Open ApexFlow Events",
  ["🔄 Verificando atualizações..."] = "🔄 Checking for updates...",
  ["🟢  PISTA VERDE"] = "🟢  GREEN TRACK",
  ["🧠 %d pista(s)"] = "🧠 %d track(s)",
},
es = {
  [" aplicado"] = " aplicado",
  [" central de IA, estratégia e direção de prova "] = " núcleo de IA, estrategia y dirección de carrera ",
  [" · faltam %d"] = " · faltan %d",
  [" · filtro ativo"] = " · filtro activo",
  ["%d carros"] = "%d coches",
  ["0 = desfile calmo · 100 = todo mundo atacando. 50 é o meio-termo."] = "0 = desfile tranquilo · 100 = todos atacando. 50 es el término medio.",
  ["1000km / 1000 Milhas (600v)"] = "1000km / 1000 Millas (600v)",
  ["12h Sebring (450v / 15 pits)"] = "12h Sebring (450v / 15 pits)",
  ["1h (60v / 2 pits)"] = "1h (60v / 2 pits)",
  ["2.4h (120v / 4 pits)"] = "2.4h (120v / 4 pits)",
  ["24h Le Mans (800v / 28 pits)"] = "24h Le Mans (800v / 28 pits)",
  ["24h Nordschleife (160v / 18 pits)"] = "24h Nordschleife (160v / 18 pits)",
  ["4h (180v / 6 pits)"] = "4h (180v / 6 pits)",
  ["6h (250v / 9 pits)"] = "6h (250v / 9 pits)",
  ["A IA tenta passar em vez de andar em fila."] = "La IA intenta adelantar en vez de ir en fila.",
  ["AI #%d — mechanical issue"] = "IA #%d — problema mecánico",
  ["AI Driver"] = "Piloto IA",
  ["Abre a janela overlay. O botão 👁 injeta 10s de FCY + punição fake (com tag PREVIEW) p/ ver o layout sem correr."] = "Abre la ventana overlay. El botón 👁 inyecta 10s de FCY + sanción falsa (con etiqueta PREVIEW) para ver el diseño sin correr.",
  ["Adds extra straight-line speed for AI by reducing their downforce profile.\n\nBest used on high-speed tracks. Ex. Monza"] = "Da más velocidad en recta a la IA reduciendo su perfil de carga.\n\nIdeal para pistas rápidas. Ej. Monza",
  ["Adjust Ratio of profile mix.\n\nChill,Balanced,Attack"] = "Ajusta la proporción de la mezcla de perfiles.\n\nChill,Balanced,Attack",
  ["Adjusts physics ratio of profiles\n0 = Base AC, no gap between Profiles\n100 = Biggest gap between profiles"] = "Ajusta la proporción de física de los perfiles\n0 = AC base, sin diferencia\n100 = Máxima diferencia",
  ["Agressividade global"] = "Agresividad global",
  ["Agressivo"] = "Agresivo",
  ["Ajuda"] = "Ayuda",
  ["Ajustes manuais (sem preset)"] = "Ajustes manuales (sin preset)",
  ["Ajustes"] = "Ajustes",
  ["Antes de largar: duração, paradas e formação."] = "Antes de salir: duración, paradas y formación.",
  ["Apaga TODOS os ajustes (perfis, limites, voz, tema). Sem desfazer."] = "Borra TODOS los ajustes (perfiles, límites, voz, tema). Sin deshacer.",
  ["ApexFlow enhances offline single-player by giving AI personality, racecraft and memory. Every driver has a class and learns corners; the field spreads naturally with hunt, hot laps and clean-air logic."] = "ApexFlow mejora el single-player offline dando a la IA personalidad, racecraft y memoria. Cada piloto tiene una clase y aprende curvas; el pelotón se estira con caza, vueltas rápidas y lógica de aire limpio.",
  ["ApexFlow modules failed to load. Check custom_shaders_patch.log for require() errors."] = "Los módulos de ApexFlow no cargaron. Revisa custom_shaders_patch.log para errores de require().",
  ["ApexFlow v"] = "ApexFlow v",
  ["ApexFlow watches every car, every frame. When a car overshoots, spins, or runs off track, it logs a hard event for that corner. Danger builds, braking starts earlier, and speed is capped. As drivers clean up their runs, confidence returns and restrictions ease. Memory persists between sessions, so each track evolves over time. Use the Clear buttons to reset a track or wipe everything if needed."] = "ApexFlow observa cada coche en cada frame. Si un coche se pasa, trompea o sale de pista, registra un evento duro en esa curva. El peligro sube, la frenada empieza antes y la velocidad se limita. Con vueltas limpias vuelve la confianza y se relajan las restricciones. La memoria persiste entre sesiones; usa los botones Clear para resetear.",
  ["App ligado"] = "App encendida",
  ["App pausado"] = "App pausada",
  ["Arredondamento dos cantos"] = "Redondeo de esquinas",
  ["Assign cars to classes in the Multi Class tab (Class 1 = fastest). Faster classes will push through traffic, while slower classes yield naturally. Use Auto-fill to split the grid by performance, or assign classes manually."] = "Asigna coches a clases en la pestaña Multi Class (Clase 1 = más rápida). Las clases rápidas abren paso en el tráfico y las lentas ceden. Usa Auto-fill para repartir por rendimiento o asigna a mano.",
  ["Ativar Estratégia de Combustível / Pit-Stops"] = "Activar estrategia de combustible / pit-stops",
  ["Ativar Largada em Movimento"] = "Activar salida lanzada",
  ["Ativar troca de pneus"] = "Activar cambio de neumáticos",
  ["Attack:   %d"] = "Ataque:   %d",
  ["Atualização disponível: v%s → v%s"] = "Actualización disponible: v%s → v%s",
  ["Atualizações"] = "Actualizaciones",
  ["Auto-fill (even split fastest→slowest)"] = "Autorrelleno (reparto equitativo más rápido→más lento)",
  ["Barras de progresso"] = "Barras de progreso",
  ["Cabeçalhos compactos (sem subtítulo)"] = "Cabeceras compactas (sin subtítulo)",
  ["Calmo"] = "Tranquilo",
  ["Cancel"] = "Cancelar",
  ["Cancelar"] = "Cancelar",
  ["Chance de volta voadora (%/volta)"] = "Probabilidad de vuelta lanzada (%/vuelta)",
  ["Changelog da v"] = "Changelog de la v",
  ["Chill:    %d"] = "Tranquilo:    %d",
  ["Chuva / Fila Única (70 km/h / 90%)"] = "Lluvia / Fila única (70 km/h / 90%)",
  ["Chuva / Fila única (70 km/h / 90%)"] = "Lluvia / Fila única (70 km/h / 90%)",
  ["Ciano"] = "Cian",
  ["Class %d%s [%d cars]"] = "Clase %d%s [%d coches]",
  ["Clear ALL track memory? Cannot be undone."] = "¿Borrar TODA la memoria de pistas? No se puede deshacer.",
  ["Clear All Tracks"] = "Borrar todas las pistas",
  ["Clear Memory (this track)"] = "Borrar memoria (esta pista)",
  ["Clear Memory: %s"] = "Borrar memoria: %s",
  ["Clear this track's learned memory?"] = "¿Borrar la memoria aprendida de esta pista?",
  ["Cleared %d corners for %s."] = "%d curvas borradas para %s.",
  ["Cleared %d tracks, %d corners total."] = "%d pistas borradas, %d curvas en total.",
  ["Club (40v / 1 pit)"] = "Club (40v / 1 pit)",
  ["Combustível Carro 0: %.1f L / %.1f L (%.0f%%)"] = "Coche 0 combustible: %.1f L / %.1f L (%.0f%%)",
  ["Combustível e pits"] = "Combustible y pits",
  ["Configuração de duração da corrida e paradas nos boxes para corridas curtas ou de Endurance (longa duração)."] = "Ajuste de duración de carrera y paradas en boxes para carreras cortas o de Endurance (larga duración).",
  ["Cor de destaque e transparência."] = "Color de acento y transparencia.",
  ["Coragem no mergulho"] = "Valentía en el ataque",
  ["Corrida"] = "Carrera",
  ["Custom"] = "Personalizado",
  ["DD: %.0f%%"] = "DD: %.0f%%",
  ["DE: %.0f%% | DD: %.0f%% | TE: %.0f%% | TD: %.0f%%"] = "DI: %.0f%% | DD: %.0f%% | TI: %.0f%% | TD: %.0f%%",
  ["DE: %.0f%%"] = "DI: %.0f%%",
  ["Dados das IAs aparecem durante a sessão."] = "Datos de las IA aparecen durante la sesión.",
  ["Deixa a IA mais rápida ou devagar no geral. 100% = jogo original."] = "Hace la IA más rápida o lenta en general. 100% = juego original.",
  ["Detalhe: "] = "Detalle: ",
  ["Difficulty Boost"] = "Impulso de dificultad",
  ["Diga as voltas; a IA calcula paradas e pneus sozinha."] = "Dime las vueltas; la IA calcula paradas y neumáticos sola.",
  ["Disponível durante a sessão de corrida."] = "Disponible durante la sesión de carrera.",
  ["Distância de separação entre as duas filas (esquerda e direita)."] = "Distancia de separación entre las dos filas (izquierda y derecha).",
  ["Duração da corrida (voltas)"] = "Duración de la carrera (vueltas)",
  ["Duração, pits, pneus e largada"] = "Duración, pits, neumáticos y salida",
  ["Dê personalidade à IA. Padrões servem p/ quase tudo."] = "Dale personalidad a la IA. Los patrones sirven para casi todo.",
  ["Empty"] = "Vacío",
  ["Empurrão na briga"] = "Empuje en la lucha",
  ["Enable Low-Downforce AI"] = "Activar IA de baja carga",
  ["Enable learning module"] = "Activar módulo de aprendizaje",
  ["Enable multiclass"] = "Activar multiclase",
  ["Enable/disable ApexFlow's adaptive corner memory.\n\nON = hard events update track memory and learned danger/caps are applied.\nOFF = no new learning and learned danger/caps are ignored, while the rest of ApexFlow still runs."] = "Activa/desactiva la memoria adaptativa de curvas.\n\nON = los eventos duros actualizan la memoria y se aplican peligro/límites.\nOFF = sin aprendizaje nuevo y se ignora lo aprendido; el resto sigue.",
  ["Enables multiclass logic so AI recognize class differences and race accordingly."] = "Activa la lógica multiclase para que la IA reconozca diferencias de clase y corra en consecuencia.",
  ["Endurance-style fuel forcing for AI. Set race length and mandatory stops; AI will pit naturally when fuel runs low. Tire change on pit stop based on wear threshold."] = "Combustible estilo Endurance para la IA. Define duración y paradas obligatorias; la IA entra sola cuando falta combustible. Cambio de neumáticos según desgaste.",
  ["Equilibrado"] = "Equilibrado",
  ["Erro ao desenhar a aba "] = "Error al dibujar la pestaña ",
  ["Erro: "] = "Error: ",
  ["Error computing stats:"] = "Error calculando estadísticas:",
  ["Escala do HUD"] = "Escala del HUD",
  ["Escolha o que o overlay mostra na corrida (gaps/PP)."] = "Elige qué muestra el overlay en carrera (gaps/PP).",
  ["Esconder parado no box (+10s)"] = "Ocultar parado en box (+10s)",
  ["Espaço para-choque a para-choque. 3.8 a 4.5m é o padrão das categorias reais."] = "Espacio paragolpes a paragolpes. 3.8 a 4.5m es el estándar de las categorías reales.",
  ["Esta build do CSP não expõe HTTP para o Lua. A verificação volta sozinha ao atualizar o CSP."] = "Esta build de CSP no expone HTTP a Lua. La comprobación vuelve sola al actualizar CSP.",
  ["Estilo"] = "Estilo",
  ["Estratégia (próximo pit / combustível)"] = "Estrategia (próximo pit / combustible)",
  ["Estratégia de Corrida & Endurance"] = "Estrategia de carrera y Endurance",
  ["Events HUD unavailable."] = "HUD de eventos no disponible.",
  ["Every AI driver is assigned a class (Chill, Normal, or Attack) which shapes how they brake, commit to passes, and handle pressure. Pace varies naturally between drivers, spreading the field instead of locking it into a train. Features like hot lap bursts, hunt mode after being passed, and clean air boosts make races feel alive rather than scripted."] = "Cada piloto IA tiene una clase (Chill, Normal o Attack) que define cómo frena, ataca y gestiona la presión. El ritmo varía entre pilotos y estira el pelotón en vez de ir en tren. Ráfagas de vuelta rápida, modo caza tras ser adelantado e impulsos de aire limpio hacen la carrera viva.",
  ["Ex: protótipos + GT. Classe 1 = mais rápida."] = "Ej.: prototipos + GT. Clase 1 = más rápida.",
  ["Extras (preset · update · detalhes)"] = "Extras (preset · update · detalles)",
  ["Filtre por nome: “pit”, “gaps”, “PP”…"] = "Filtrar por nombre: “pit”, “gaps”, “PP”…",
  ["Force Scan AI Drivers"] = "Forzar escaneo de pilotos IA",
  ["Formação 2x2 lado a lado na volta de apresentação, com velocidade controlada e relargada realista na reta principal ao receber a bandeira verde."] = "Formación 2x2 lado a lado en la vuelta de presentación, con velocidad controlada y relanzada realista en la recta principal con bandera verde.",
  ["Força do ritmo ( Pace )"] = "Fuerza del ritmo (Pace)",
  ["Fuel Strategy"] = "Estrategia de combustible",
  ["Gaps & Penalty Severity (v0.25.0+)"] = "Gaps y severidad de sanción (v0.25.0+)",
  ["Gaps (atrás / setor) · PP"] = "Gaps (detrás / sector) · PP",
  ["Gaps (atrás / setor) — PP"] = "Gaps (detrás / sector) — PP",
  ["GitHub Update Checker"] = "Comprobador de actualizaciones de GitHub",
  ["IA que aprende"] = "IA que aprende",
  ["Idioma"] = "Idioma",
  ["Independent race suite for Assetto Corsa — offline AI, strategy & race control."] = "Suite de carreras independiente para Assetto Corsa — IA offline, estrategia y dirección de carrera.",
  ["Intensidade da física"] = "Intensidad de la física",
  ["Intervalo entre verificações (horas)"] = "Intervalo entre comprobaciones (horas)",
  ["Início"] = "Inicio",
  ["Laranja Apex"] = "Naranja Apex",
  ["Largada em Movimento Realista (Rolling Start)"] = "Salida lanzada realista (Rolling Start)",
  ["Largada em movimento"] = "Salida lanzada",
  ["Learning (pistas memorizadas)"] = "Learning (pistas memorizadas)",
  ["Learning Module"] = "Módulo de aprendizaje",
  ["Learning is OFF: existing memory is preserved, but not applied or updated."] = "Aprendizaje OFF: la memoria existente se conserva, pero no se aplica ni se actualiza.",
  ["Leigo: controla o quanto as IAs brigam por posição em vez de andar em fila.\nTécnico: impaciência atrás (stuckRamp), janela de mergulho (draft commit) e empurrão."] = "Simple: cuánto pelean las IA por posición en vez de ir en fila.\nTécnico: impaciencia detrás (stuckRamp), ventana de ataque (draft commit) y empuje.",
  ["Leigo: deixa o HUD menor e mais denso.\nTécnico: pula separadores e textos secundários."] = "Simple: deja el HUD más pequeño y denso.\nTécnico: omite separadores y textos secundarios.",
  ["Leigo: escolha o que aparece no overlay ApexFlow Events (gaps/PP).\nTécnico: cada seção lê o estado do seu módulo; desligar esconde só o visual."] = "Simple: elige qué muestra el overlay ApexFlow Events (gaps/PP).\nTécnico: cada sección lee su módulo; apagar solo oculta lo visual.",
  ["Leigo: esconde as linhas de explicação das abas, deixa tudo menor.\nTécnico: pula o subtitle em cardTitle()."] = "Simple: oculta las líneas de explicación de las pestañas, todo más pequeño.\nTécnico: omite el subtítulo en cardTitle().",
  ["Leigo: mostra quem vai parar e quando.\nTécnico: próximos pitLaps calculados + combustível restante/aprendido."] = "Simple: muestra quién para y cuándo.\nTécnico: próximos pitLaps calculados + combustible restante/aprendido.",
  ["Leigo: mude a cor de destaque e a transparência do fundo.\nTécnico: cor de destaque (accent) e alfa do WindowBg/ChildBg."] = "Simple: cambia el color de acento y la transparencia del fondo.\nTécnico: color de acento y alfa de WindowBg/ChildBg.",
  ["Leigo: no box parado o painel dorme sozinho e volta na pista.\nTécnico: gate por isInPitlane/isInPit + speed < 5 por 10s."] = "Simple: parado en boxes el panel duerme solo y vuelve en pista.\nTécnico: puerta por isInPitlane/isInPit + velocidad < 5 durante 10s.",
  ["Leigo: preset atual, aviso de update, marcha/pneus/paradas da IA.\nTécnico: lê githubGetState e strategy.getState (gaps/PP)."] = "Simple: preset actual, aviso de update, marcha/neumáticos/paradas de la IA.\nTécnico: lee githubGetState y strategy.getState (gaps/PP).",
  ["Lembra onde erra e melhora com o tempo."] = "Recuerda dónde falla y mejora con el tiempo.",
  ["Live gaps to the car behind and sector deltas to P1, plus a penalty-severity counter (PP) for regulatory awareness. AC-native race control handles flags and limits."] = "Gaps en vivo con el coche de detrás y deltas de sector con P1, más contador de severidad (PP). El control de carrera nativo de AC gestiona banderas y límites.",
  ["Low-Downforce"] = "Baja carga",
  ["Manual class assignment for this session. Class 1 = fastest."] = "Asignación manual de clases para esta sesión. Clase 1 = más rápida.",
  ["Marque o que quer ver no overlay:"] = "Marca qué ver en el overlay:",
  ["Modo compacto (menos espaçamento)"] = "Modo compacto (menos espacio)",
  ["Module status:"] = "Estado de módulos:",
  ["Multiclass is OFF. Class assignments + class-based AI are not applied."] = "Multiclase OFF. Asignaciones de clase + IA por clase no aplicadas.",
  ["Multiclass"] = "Multiclase",
  ["Nenhuma verificação realizada ainda."] = "Ninguna comprobación realizada aún.",
  ["No AI car data found yet (data may still be loading)."] = "Aún no hay datos de coches IA (pueden estar cargando).",
  ["No AI data yet."] = "Aún no hay datos de IA.",
  ["Normal:   %d"] = "Normal:   %d",
  ["Nothing to clear for %s."] = "Nada que borrar para %s.",
  ["Nothing to clear."] = "Nada que borrar.",
  ["Não consegui abrir sozinho. Digite no navegador:"] = "No pude abrirlo solo. Escríbelo en el navegador:",
  ["O que aparece correndo."] = "Lo que aparece corriendo.",
  ["O que cada parte faz, em linguagem simples."] = "Qué hace cada parte, en lenguaje simple.",
  ["O restante do app continua funcionando. Envie esse texto ao suporte."] = "El resto de la app sigue funcionando. Envía este texto al soporte.",
  ["Overlay window with live gaps, PP and strategy. Enable it in Content Manager → Apps → ApexFlow Events. Fully customizable in the HUD tab (gaps/PP only, AC-native flags)."] = "Ventana overlay con gaps, PP y estrategia en vivo. Actívala en Content Manager → Apps → ApexFlow Events. Totalmente personalizable en la pestaña HUD (solo gaps/PP, banderas nativas de AC).",
  ["P%d   ·   V%d   ·   %d km/h   ·   %.1fL"] = "P%d   ·   V%d   ·   %d km/h   ·   %.1fL",
  ["P%d   ·   V%d   ·   %d km/h   ·   M%d"] = "P%d   ·   V%d   ·   %d km/h   ·   M%d",
  ["PRESET"] = "PRESET",
  ["Padrões de volta"] = "Patrones de vuelta",
  ["Painel na tela"] = "Panel en pantalla",
  ["Painel na tela, telemetria e voz"] = "Panel en pantalla, telemetría y voz",
  ["Para atualizar: baixe a última release e substitua a pasta apps/lua/ApexFlow."] = "Para actualizar: descarga la última release y sustituye la carpeta apps/lua/ApexFlow.",
  ["Paradas obrigatórias nos boxes"] = "Paradas obligatorias en boxes",
  ["Personalidade, brigas e aprendizado da IA"] = "Personalidad, luchas y aprendizaje de la IA",
  ["Physics Intensity"] = "Intensidad de física",
  ["Pilotos"] = "Pilotos",
  ["Piscar alertas críticos"] = "Parpadear alertas críticas",
  ["Pistas de reta (Monza)"] = "Pistas de recta (Monza)",
  ["Pneus (Frente): "] = "Neumáticos (del.): ",
  ["Pneus (Trás):    "] = "Neumáticos (tras.):    ",
  ["Ponto em que a bandeira verde é acionada. 92% a 96% corresponde à entrada da reta principal."] = "Punto donde sale la bandera verde. 92% a 96% es la entrada de la recta principal.",
  ["Posição / volta / velocidade"] = "Posición / vuelta / velocidad",
  ["Predefinições Reais de Largada:"] = "Preajustes reales de salida:",
  ["Predefinições Rápidas (Endurance & 24 Horas):"] = "Preajustes rápidos (Endurance y 24 Horas):",
  ["Predefinições:"] = "Preajustes:",
  ["Preset"] = "Preset",
  ["Profile Gap"] = "Brecha de perfiles",
  ["Profile Mix"] = "Mezcla de perfiles",
  ["Profiles:"] = "Perfiles:",
  ["Publicado em: "] = "Publicado en: ",
  ["Quanto o grid briga"] = "Cuánto pelea la parrilla",
  ["RACE EVENTS"] = "EVENTOS DE CARRERA",
  ["Race Events HUD — Personalização"] = "Race Events HUD — Personalización",
  ["Race Events HUD"] = "HUD de eventos de carrera",
  ["Racecraft (brigas e ultrapassagens)"] = "Racecraft (luchas y adelantamientos)",
  ["Realistic formation lap with 2x2 grid, pace car speed control, and green flag release on the main straight. Supports dj_safety_car or pole-sitter led formations."] = "Vuelta de formación realista con parrilla 2x2, control de velocidad del pace car y salida con verde en la recta principal. Soporta dj_safety_car o formación liderada por la pole.",
  ["Repositório: "] = "Repositorio: ",
  ["Ritmo e dificuldade"] = "Ritmo y dificultad",
  ["Rolling Start"] = "Salida lanzada",
  ["Rosa"] = "Rosa",
  ["Roxo"] = "Morado",
  ["SEÇÕES"] = "SECCIONES",
  ["Salvo"] = "Guardado",
  ["Se ativado, durante a parada forçada nos boxes, a IA verificará o desgaste dos pneus. Se o estado estiver abaixo do limite configurado, pneus novos serão colocados junto com o reabastecimento."] = "Si está activado, durante la parada forzada en boxes la IA comprobará el desgaste. Si está bajo el límite, pondrá neumáticos nuevos con el repostaje.",
  ["Sem sessão — números vivos aparecem em pista "] = "Sin sesión — los números vivos aparecen en pista ",
  ["Sem sessão — o placar acende em pista "] = "Sin sesión — el marcador enciende en pista ",
  ["Sessão (pista / tempo restante)"] = "Sesión (pista / tiempo restante)",
  ["Show window in setup"] = "Mostrar ventana en ajustes",
  ["Sim, restaurar"] = "Sí, restaurar",
  ["Slider adjusts physics ratio.\n\n0 = Base AC AI\n100 = Full ApexFlow physics"] = "El deslizador ajusta la proporción de física.\n\n0 = IA base de AC\n100 = Física ApexFlow completa",
  ["Sprint (20v / 1 pit)"] = "Sprint (20v / 1 pit)",
  ["Stacks on top of AC difficulty.\n\n100% = no change\nHigher = faster AI overall."] = "Se suma a la dificultad de AC.\n\n100% = sin cambio\nMás alto = IA más rápida en general.",
  ["Só mexa p/ pistas de alta velocidade."] = "Solo toca para pistas de alta velocidad.",
  ["TD: %.0f%%"] = "TD: %.0f%%",
  ["TE: %.0f%%"] = "TI: %.0f%%",
  ["Tela&Voz"] = "Pantalla&Voz",
  ["Telemetria disponível durante a sessão de corrida."] = "Telemetría disponible durante la sesión de carrera.",
  ["Telemetria do carro ativo disponível durante a sessão."] = "Telemetría del coche activo disponible durante la sesión.",
  ["Telemetria viva da sessão"] = "Telemetría viva de la sesión",
  ["Tempo colado até atacar (s)"] = "Tiempo pegado hasta atacar (s)",
  ["The Core"] = "El núcleo",
  ["Top-Speed Strength"] = "Fuerza de velocidad punta",
  ["Total AI: %d"] = "IA total: %d",
  ["Total Classes"] = "Clases totales",
  ["Transparência do fundo"] = "Transparencia del fondo",
  ["Troca de Pneus"] = "Cambio de neumáticos",
  ["Trocar pneus quando estado ≤"] = "Cambiar neumáticos cuando el estado ≤",
  ["Turquesa"] = "Turquesa",
  ["Ultrapassagens de verdade"] = "Adelantamientos de verdad",
  ["Velocidade limite durante a volta de formação."] = "Velocidad límite durante la vuelta de formación.",
  ["Ver se saiu versão nova."] = "Ver si salió versión nueva.",
  ["Verde"] = "Verde",
  ["Verifica releases no GitHub via API (requer CSP com ac.webRequest)."] = "Comprueba releases en GitHub vía API (requiere CSP con ac.webRequest).",
  ["Verificando atualizações..."] = "Buscando actualizaciones...",
  ["Verificar na inicialização"] = "Comprobar al iniciar",
  ["Verificação Automática"] = "Comprobación automática",
  ["Verificação automática indisponível"] = "Comprobación automática no disponible",
  ["Vermelho"] = "Rojo",
  ["Versão atualizada (v"] = "Versión actualizada (v",
  ["Versão instalada: v"] = "Versión instalada: v",
  ["Visual"] = "Visual",
  ["Visual, atualizações e bastidores"] = "Visual, actualizaciones y bastidores",
  ["Visual, updates e bastidores. Mexa uma vez e esqueça."] = "Visual, actualizaciones e interior. Ajusta una vez y olvida.",
  ["Volta de apresentação em fila antes da verde. Vem desligado."] = "Vuelta de presentación en fila antes de la verde. Viene apagado.",
  ["Voltas da prova (auto): %d"] = "Vueltas de carrera (auto): %d",
  ["Voltas da prova (manual): %d"] = "Vueltas de carrera (manual): %d",
  ["Várias categorias juntas"] = "Varias categorías juntas",
  ["X"] = "X",
  ["Yes"] = "Sí",
  ["Yes, clear all"] = "Sí, borrar todo",
  ["armado"] = "armado",
  ["central de IA, estratégia e direção de prova "] = "núcleo de IA, estrategia y dirección de carrera ",
  ["de %dv (auto)"] = "de %dv (auto)",
  ["de %dv"] = "de %dv",
  ["manual"] = "manual",
  ["nova!"] = "¡nueva!",
  ["pit v"] = "pit v",
  ["sem pit"] = "sin pit",
  ["v/"] = "v/",
  ["ℹ Verificação automática indisponível"] = "ℹ Comprobación automática no disponible",
  ["⌨ filtrar…"] = "⌨ filtrar…",
  ["⏱ Setor %d: +%.2fs p/ P1"] = "⏱ Sector %d: +%.2fs para P1",
  ["○ box"] = "○ box",
  ["⚖ PP: limpo"] = "⚖ PP: limpio",
  ["⚙ App"] = "⚙ App",
  ["⚙️ Ajustes"] = "⚙️ Ajustes",
  ["⚠ Rolling Start pode não funcionar: funções de física ausentes nesta build do CSP."] = "⚠ El Rolling Start puede no funcionar: faltan funciones de física en esta build de CSP.",
  ["⚠️ Voltar aos padrões?"] = "⚠️ ¿Volver a los patrones?",
  ["⚪ Formação liderada pelo Pole Position (ou adicione o dj_safety_car no grid)."] = "⚪ Formación liderada por la Pole Position (o añade dj_safety_car a la parrilla).",
  ["⛽ %.1f L (%d%%)"] = "⛽ %.1f L (%d%%)",
  ["⛽ Pit: volta %d%s%s"] = "⛽ Pit: vuelta %d%s%s",
  ["⛽ Sem pit agendado"] = "⛽ Sin pit programado",
  ["⛽ box AGORA (tanque no fim)"] = "⛽ box AHORA (depósito al final)",
  ["⛽ box em ~%dv (%.1f L/volta)"] = "⛽ box en ~%dv (%.1f L/vuelta)",
  ["✓ Verificando atualizações..."] = "✓ Buscando actualizaciones...",
  ["✓ Versão atualizada (v"] = "✓ Versión actualizada (v",
  ["✓ padrões"] = "✓ patrones",
  ["❌ Erro ao desenhar a aba "] = "❌ Error al dibujar la pestaña ",
  ["❌ Erro: "] = "❌ Error: ",
  ["🅿 no box — HUD pausado (volte à pista p/ reativar)"] = "🅿 en box — HUD pausado (vuelve a pista para reactivar)",
  ["🌐 Abrir Release"] = "🌐 Abrir Release",
  ["🌐 Abrir página de Releases"] = "🌐 Abrir página de Releases",
  ["🎉 Atualização disponível: v%s → v%s"] = "🎉 Actualización disponible: v%s → v%s",
  ["🎨 Aparência"] = "🎨 Apariencia",
  ["🏁 Corrida"] = "🏁 Carrera",
  ["🏁 Monitor de Endurance & Telemetria"] = "🏁 Monitor de Endurance y telemetría",
  ["🏁 Você na volta %d"] = "🏁 Vas en la vuelta %d",
  ["👁 Testar HUD"] = "👁 Probar HUD",
  ["💾 Salvar"] = "💾 Guardar",
  ["📊 Painel"] = "📊 Panel",
  ["📏 +%dm p/ P1"] = "📏 +%dm para P1",
  ["📏 P1 +%d volta(s)"] = "📏 P1 +%d vuelta(s)",
  ["📏 VOCÊ LIDERA"] = "📏 LIDERAS",
  ["📚 %d pista(s)"] = "📚 %d pista(s)",
  ["📚 sem dados"] = "📚 sin datos",
  ["📡 Tela & Voz"] = "📡 Pantalla y voz",
  ["📺 Abrir ApexFlow Events"] = "📺 Abrir ApexFlow Events",
  ["🔄 Padrões"] = "🔄 Patrones",
  ["🔄 Verificando atualizações..."] = "🔄 Buscando actualizaciones...",
  ["🔍 Verificar Agora"] = "🔍 Comprobar ahora",
  ["🔙 %.0fm"] = "🔙 %.0fm",
  ["🔙 Atrás: %.0fm (P%d)"] = "🔙 Detrás: %.0fm (P%d)",
  ["🔙 sem carro atrás"] = "🔙 sin coche detrás",
  ["🟢  PISTA VERDE"] = "🟢  PISTA VERDE",
  ["🟢 PISTA VERDE"] = "🟢 PISTA VERDE",
  ["🟢 Pace Car Detectado: Toyota ACTC (dj_safety_car) na liderança!"] = "🟢 ¡Pace Car detectado: Toyota ACTC (dj_safety_car) en cabeza!",
  ["🟢 Pace Car Detectado: dj_safety_car"] = "🟢 Pace Car detectado: dj_safety_car",
  ["🟢 pista verde — AC nativo"] = "🟢 pista verde — AC nativo",
  ["🤖 Estratégia das IAs ao vivo"] = "🤖 Estrategia de las IA en vivo",
  ["🤖 Pilotos"] = "🤖 Pilotos",
  ["🧠 %d pista(s)"] = "🧠 %d pista(s)",

} }

function M.setLang(l)
  if type(l) ~= "string" then return end
  l = l:lower():sub(1, 2)
  if l == "pt" or l == "en" or l == "es" then M._lang = l end
end

function M.getLang() return M._lang end

-- normaliza p/ busca tolerante (acentos/caixa/espaço): "Padrões" == "padroes"
local ACC = { ["á"] = "a", ["à"] = "a", ["â"] = "a", ["ã"] = "a", ["ä"] = "a",
  ["é"] = "e", ["è"] = "e", ["ê"] = "e", ["ë"] = "e",
  ["í"] = "i", ["ì"] = "i", ["î"] = "i", ["ï"] = "i",
  ["ó"] = "o", ["ò"] = "o", ["ô"] = "o", ["õ"] = "o", ["ö"] = "o",
  ["ú"] = "u", ["ù"] = "u", ["û"] = "u", ["ü"] = "u",
  ["ç"] = "c", ["ñ"] = "n",
  ["Á"] = "a", ["À"] = "a", ["Â"] = "a", ["Ã"] = "a", ["Ä"] = "a",
  ["É"] = "e", ["È"] = "e", ["Ê"] = "e", ["Ë"] = "e",
  ["Í"] = "i", ["Ì"] = "i", ["Î"] = "i", ["Ï"] = "i",
  ["Ó"] = "o", ["Ò"] = "o", ["Ô"] = "o", ["Õ"] = "o", ["Ö"] = "o",
  ["Ú"] = "u", ["Ù"] = "u", ["Û"] = "u", ["Ü"] = "u",
  ["Ç"] = "c", ["Ñ"] = "n" }
local function norm(s)
  s = tostring(s or ""):lower()
  s = s:gsub("\194\160", " ")
  s = s:gsub("%s+", " "):gsub("^%s+", ""):gsub("%s+$", "")
  for a, b in pairs(ACC) do s = s:gsub(a, b) end
  return s
end

local NORMDICT = {}
local function rebuild()
  NORMDICT = {}
  for lang, dict in pairs(M.DICT) do
    local nd = {}
    for k, v in pairs(dict) do nd[norm(k)] = v end
    NORMDICT[lang] = nd
  end
end

function M.L(s)
  if type(s) ~= "string" then return s end
  local lang = M._lang
  if not lang or lang == "pt" then return s end
  local nd = NORMDICT[lang] or {}
  -- preserva ##id dos widgets (traduz só o rótulo)
  local p = s:find("##", 1, true)
  if p then
    local t = nd[norm(s:sub(1, p - 1))]
    if t and t ~= "" then return t .. s:sub(p) end
    return s
  end
  local t = nd[norm(s)]
  if t and t ~= "" then return t end
  return s
end

rebuild()

return M
